import '../models/category.dart';
import '../models/listing.dart';

/// Demo/fallback data for the marketplace
const demoCategories = [
  Category(id: 'cars', name: 'Cars', slug: 'cars', sortOrder: 1, isActive: true),
  Category(id: 'real-estate', name: 'Real Estate', slug: 'real-estate', sortOrder: 2, isActive: true),
  Category(id: 'electronics', name: 'Electronics', slug: 'electronics', sortOrder: 3, isActive: true),
  Category(id: 'furniture', name: 'Furniture', slug: 'furniture', sortOrder: 4, isActive: true),
  Category(id: 'services', name: 'Services', slug: 'services', sortOrder: 5, isActive: true),
  Category(id: 'other', name: 'Other', slug: 'other', sortOrder: 6, isActive: true),
];

final demoListings = [
  Listing(
    id: 'demo-1',
    title: 'Toyota Land Cruiser GXR 2021',
    description: 'Clean title, full service history, leather interior, ready for inspection.',
    price: 58500,
    city: 'Baghdad',
    categoryId: 'cars',
    categoryName: 'Cars',
    status: 'active',
    views: 1240,
    favoritesCount: 86,
    isFeatured: true,
    isTop: true,
    userName: 'Karrar Motors',
    userRating: 4.8,
    primaryImage: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=900&q=80',
    createdAt: DateTime.now(),
  ),
  Listing(
    id: 'demo-2',
    title: 'Modern family house near Erbil Citadel',
    description: 'Three bedrooms, private garden, parking, and a bright open living space.',
    price: 185000,
    city: 'Erbil',
    categoryId: 'real-estate',
    categoryName: 'Real Estate',
    status: 'active',
    views: 856,
    favoritesCount: 44,
    isFeatured: true,
    userName: 'Darin Properties',
    userRating: 4.6,
    primaryImage: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=80',
    createdAt: DateTime.now(),
  ),
  Listing(
    id: 'demo-3',
    title: 'iPhone 15 Pro Max - Original sealed box',
    description: 'Latest model with warranty card and accessories. International version.',
    price: 1450,
    city: 'Basra',
    categoryId: 'electronics',
    categoryName: 'Electronics',
    status: 'active',
    views: 2105,
    favoritesCount: 156,
    isTop: true,
    userName: 'Tech Hub Basra',
    userRating: 4.9,
    primaryImage: 'https://images.unsplash.com/photo-1592286927505-1def25115558?auto=format&fit=crop&w=900&q=80',
    createdAt: DateTime.now(),
  ),
  Listing(
    id: 'demo-4',
    title: 'Luxury leather sofa set - 6 seater',
    description: 'Italian leather, barely used, needs space. Perfect condition for home office.',
    price: 2800,
    city: 'Sulaimaniya',
    categoryId: 'furniture',
    categoryName: 'Furniture',
    status: 'active',
    views: 432,
    favoritesCount: 23,
    userName: 'Home Comfort',
    userRating: 4.4,
    primaryImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80',
    createdAt: DateTime.now(),
  ),
  Listing(
    id: 'demo-5',
    title: 'Professional web design service',
    description: 'Responsive websites for businesses, e-commerce, and portfolios. SEO included.',
    price: 500,
    city: 'Baghdad',
    categoryId: 'services',
    categoryName: 'Services',
    status: 'active',
    views: 678,
    favoritesCount: 12,
    userName: 'Digital Agency Pro',
    userRating: 4.7,
    primaryImage: 'https://images.unsplash.com/photo-1460925895917-adf4e565db18?auto=format&fit=crop&w=900&q=80',
    createdAt: DateTime.now(),
  ),
  Listing(
    id: 'demo-6',
    title: 'BMW X5 2020 - Excellent condition',
    description: 'Full service record, low mileage, panoramic roof, navigation system.',
    price: 72000,
    city: 'Najaf',
    categoryId: 'cars',
    categoryName: 'Cars',
    status: 'active',
    views: 945,
    favoritesCount: 67,
    userName: 'Premium Auto',
    userRating: 4.5,
    primaryImage: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=900&q=80',
    createdAt: DateTime.now(),
  ),
  Listing(
    id: 'demo-7',
    title: 'Commercial space for rent - High traffic area',
    description: '300 sqm shop, ground floor, parking available, near metro station.',
    price: 3500,
    city: 'Baghdad',
    categoryId: 'real-estate',
    categoryName: 'Real Estate',
    status: 'active',
    views: 523,
    favoritesCount: 31,
    userName: 'Commercial Realty',
    userRating: 4.3,
    primaryImage: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=900&q=80',
    createdAt: DateTime.now(),
  ),
  Listing(
    id: 'demo-8',
    title: 'Samsung 65" 4K QLED TV - Smart TV',
    description: 'Latest model, with remote control and wall mount. Energy efficient.',
    price: 950,
    city: 'Erbil',
    categoryId: 'electronics',
    categoryName: 'Electronics',
    status: 'active',
    views: 1876,
    favoritesCount: 124,
    isFeatured: true,
    userName: 'Electronics Store',
    userRating: 4.8,
    primaryImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    createdAt: DateTime.now(),
  ),
];
